title: Impulsive Updates
email: Xer0.Puls3.XXII@gmail.com
description: >-
    This is an informative collection of what I deem important about selective topics.
baseurl: "/blog"
url: "https://xPuls3.GitHub.io"

minima:
    date_format: "%b %-d, %Y"

    # generate social links in footer
    social_links:
        twitter: jekyllrb
        github:  jekyll
        rss: rss
        # devto: jekyll
        # dribbble: jekyll
        # facebook: jekyll
        # flickr:   jekyll
        # instagram: jekyll
        # linkedin: jekyll
        # pinterest: jekyll
        # youtube: jekyll
        # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
        # youtube_channel_name: CloudCannon
        # telegram: jekyll
        # googleplus: +jekyll
        # microdotblog: jekyll
        # keybase: jekyll

        # Mastodon instances
        # mastodon:
        # - username: jekyll
        #   instance: example.com
        # - username: jekyll2
        #   instance: example.com

        # GitLab instances
        # gitlab:
        # - username: jekyll
        #   instance: example.com
        # - username: jekyll2
        #   instance: example.com

disqus:
    shortname: https-xpuls3-github-io-blog

google_analytics: UA-149595553-1
theme: minima
permalink: /:categories/:title/

collections:
    category:
        output: true

referral:
    Pendoria:
        Puls3: "https://pendoria.net/?ref=334"
        clean: "https://pendoria.net/"
    Avabur:
        Puls3: "https://www.avabur.com/?ref=16595"
        clean: "https://www.avabur.com/"
    IQRPG:
        Puls3: "https://www.iqrpg.com/?r=51"
        clean: "https://www.iqrpg.com/"
    Lyrania:
        clean: "http://lyrania.co.uk/"
    DSRPG:
        Puls3: "http://dsrpg.co/?ref=245"
        clean: "http://dsrpg.co/"

plugins:
    - jekyll-feed

exclude:
    - build.bat
    - .idea